---
title: "Exploratory Articles"
theme: "588157"
format:
  exploratory-pdf: 
    keep-tex: true
  exploratory-html: default
author:
  - name: John Doe
    affiliations:
      - name: Dummy org
        department: Cool Dep
        address: Somewhere
        city: Magic city
        country: best one
        postal-code: 9999
      - Demo Journal
    orcid: 0000-0000-0000-0000
    email: JD@example.org
    url: https://example.org/
  - name: his friend
    affiliations:
      - Another Affiliation
abstract: |
  This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.   This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.
keywords: [template, demo]
reference-section-title: References
bibliography: bibliography.bib  
---

## Introduction
This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template. 

### Subheader

#### SubSubHeader

## Methodology

## Results

## Conclusions

  This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.   This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.This document is only a demo explaining how to use the template.